'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Heart, LogOut, Package, UserRound } from 'lucide-react';
import { useAuth } from '@/components/auth';
import { api } from '@/lib/api';
type Order = { id: string; orderNumber: string; status: string; total: number; createdAt: string; items: { name: string; quantity: number; size: string }[] };
export default function AccountPage() { const { user, ready, wishlist, logout } = useAuth(); const router = useRouter(); const [orders, setOrders] = useState<Order[]>([]); useEffect(() => { if (ready && !user) router.replace('/login'); if (user) api<Order[]>('/users/me/orders').then(setOrders).catch(() => {}); }, [ready, user, router]); if (!ready || !user) return <div className="py-32 text-center text-sm text-muted">Loading account…</div>; return <div className="mx-auto max-w-[1180px] px-5 py-14 sm:px-8"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[10px] font-bold tracking-[.3em] text-muted uppercase">My account</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.05em] uppercase">Hello, {user.name.split(' ')[0]}</h1><p className="mt-2 text-sm text-muted">{user.email}</p></div><button onClick={() => { logout(); router.push('/'); }} className="flex items-center gap-2 border border-ink px-5 py-3 text-xs font-bold uppercase"><LogOut size={15} /> Sign out</button></header><div className="mt-10 grid gap-4 sm:grid-cols-3"><Card icon={<Package />} label="Orders" value={orders.length} /><Card icon={<Heart />} label="Wishlist" value={wishlist.size} href="/wishlist" /><Card icon={<UserRound />} label="Membership" value="Active" /></div><section className="mt-10 border border-line"><div className="border-b border-line p-5"><h2 className="text-lg font-extrabold uppercase">Order history</h2></div>{orders.map(order => <div key={order.id} className="grid gap-3 border-b border-line p-5 last:border-0 sm:grid-cols-[1fr_1fr_auto] sm:items-center"><div><p className="text-sm font-bold">{order.orderNumber}</p><p className="text-xs text-muted">{new Date(order.createdAt).toLocaleDateString()}</p></div><p className="text-xs text-muted">{order.items.map(item => `${item.name} × ${item.quantity}`).join(', ')}</p><div className="sm:text-right"><p className="font-bold">৳{order.total.toLocaleString()}</p><span className="text-[10px] font-bold uppercase">{order.status}</span></div></div>)}{orders.length === 0 && <div className="p-10 text-center"><p className="text-sm text-muted">You have not placed an order yet.</p><Link href="/shop" className="mt-4 inline-block text-xs font-bold underline">Start shopping</Link></div>}</section></div>; }
function Card({ icon, label, value, href }: { icon: React.ReactNode; label: string; value: string | number; href?: string }) { const content = <div className="border border-line p-5"><span className="text-muted">{icon}</span><p className="mt-5 text-[10px] font-bold tracking-[.2em] text-muted uppercase">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}</p></div>; return href ? <Link href={href}>{content}</Link> : content; }
